name: Check

on:
  push:
    branches: [main]
    paths-ignore: ['src/content/**']
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.tool-versions'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run checks
        run: pnpm check
